### ISSUE TITLE
Rotation issue in with Proper scroll example

### ISSUE THREAD

**Issue by mukyasa** [DoddaSrinivasan/iOSCircularCollectionView#1]
The cells are not rotated properly when i am using your configuration for Proper scroll 
 `  [circularLayout setStartAngle:M_PI endAngle:0];`
   ` circularLayout.mirrorX = NO;`
   ` circularLayout.mirrorY = YES;`

can u guide me in this

**Comment by DoddaSrinivasan** [comment]
What do you mean by not rotated properly. Can you attach some screen shot as a reference and explain what is expected and actual outcome?

**Comment by mukyasa** [comment]
the way you shared screenshot of example for **Proper scroll** the other cells are not rotated properly when i use above configuration

basically `circularLayout.rotateItems = YES;` is not working properly see the angle of 3 and 5 and 2 and 3 etc

so when u scroll they rotate weirdly

but the rotation works properly in reverse scroll not in proper scroll


![simulator screen shot 28-feb-2017 5 10 24 pm](https://cloud.githubusercontent.com/assets/7480780/23404006/d47c2840-fdd8-11e6-8700-30d74736bb7e.png)

**Comment by DoddaSrinivasan** [comment]
Got it. I fixed it. Can you take the latest pull and check.

**Comment by mukyasa** [comment]
Thanks bro, for a quick response really appreciate your work

Can u help i am trying to show only three cells a time the way you did when
first time you load collectionview,

But when i scroll the collection and when it halts it can show 4 cells,

I want only 3 cells at a time even when user scroll . Thnks in advance
